"""initial schema

Revision ID: bbc84939231e
Revises: 
Create Date: 2026-09-15 22:20:07.600596

"""
from alembic import op
import sqlalchemy as sa
import app.models  # custom types (UTCDateTime) referenced by autogenerate


revision = 'bbc84939231e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scientific_name', sa.String(length=160), nullable=True),
    sa.Column('root_depth_mm', sa.Float(), nullable=False),
    sa.Column('maturity_days', sa.Integer(), nullable=True),
    sa.Column('stage_params', sa.JSON(), nullable=False),
    sa.Column('advisory_key', sa.String(length=120), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('due_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_due', ['status', 'due_at'], unique=False)

    op.create_table('soil_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('field_capacity_pct', sa.Float(), nullable=False),
    sa.Column('wilting_point_pct', sa.Float(), nullable=False),
    sa.Column('bulk_density', sa.Float(), nullable=True),
    sa.Column('water_holding_capacity_mm_per_m', sa.Float(), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('label_key', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('farmer', 'agronomist', 'admin', name='role'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_level', sa.String(length=16), nullable=False),
    sa.Column('channel_push', sa.Boolean(), nullable=False),
    sa.Column('channel_email', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat_key', sa.String(length=16), nullable=False),
    sa.Column('generated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('min_c', sa.Float(), nullable=True),
    sa.Column('max_c', sa.Float(), nullable=True),
    sa.Column('rain_prob_pct', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('et0_mm', sa.Float(), nullable=True),
    sa.Column('condition_code', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_key', 'day', 'generated_at', name='uq_weather_fc')
    )
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_forecasts_lat_key'), ['lat_key'], unique=False)

    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat_key', sa.String(length=16), nullable=False),
    sa.Column('observed_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_kmh', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('et0_mm', sa.Float(), nullable=True),
    sa.Column('tmax_c', sa.Float(), nullable=True),
    sa.Column('tmin_c', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_key', 'observed_at', name='uq_weather_obs')
    )
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.create_index('ix_weather_obs_latkey_ts', ['lat_key', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_observations_lat_key'), ['lat_key'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=True),
    sa.Column('previous_json', sa.JSON(), nullable=True),
    sa.Column('new_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_user_ts', ['user_id', 'created_at'], unique=False)

    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=8), nullable=False),
    sa.Column('assigned_agronomist_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agronomist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title_key', sa.String(length=120), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('channel_delivered', sa.String(length=40), nullable=True),
    sa.Column('read_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notification_dedupe')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notif_user_unread', ['user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('area_unit', sa.String(length=8), nullable=False),
    sa.Column('soil_type_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('growth_stage', sa.Enum('GERMINATION', 'VEGETATIVE', 'FLOWERING', 'FRUITING', 'MATURITY', 'HARVEST', name='growthstage'), nullable=False),
    sa.Column('sow_date', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('irrigation_method', sa.Enum('drip', 'sprinkler', 'flood', 'furrow', 'manual', 'other', name='irrigationmethod'), nullable=False),
    sa.Column('water_source', sa.String(length=80), nullable=True),
    sa.Column('boundary_geojson', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['soil_type_id'], ['soil_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_farm_id'), ['farm_id'], unique=False)

    op.create_table('advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisories_field_id'), ['field_id'], unique=False)

    op.create_table('irrigation_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('irrigation_needed', sa.Boolean(), nullable=False),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgency'), nullable=False),
    sa.Column('recommended_time_key', sa.String(length=60), nullable=False),
    sa.Column('window_start', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('window_end', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('water_mm', sa.Float(), nullable=True),
    sa.Column('liters', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('confidence_factors_json', sa.JSON(), nullable=False),
    sa.Column('inputs_digest_json', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('override_action', sa.String(length=16), nullable=True),
    sa.Column('override_reason', sa.String(length=1000), nullable=True),
    sa.Column('override_by', sa.Integer(), nullable=True),
    sa.Column('override_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['override_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('irrigation_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_irrigation_recommendations_field_id'), ['field_id'], unique=False)
        batch_op.create_index('ix_rec_field_computed', ['field_id', 'computed_at'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('device_identifier', sa.String(length=120), nullable=False),
    sa.Column('device_key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', name='sensorstatus'), nullable=False),
    sa.Column('installed_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_identifier')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_field_id'), ['field_id'], unique=False)

    op.create_table('soil_moisture_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value_pct', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'sensor', name='readingsource'), nullable=False),
    sa.Column('taken_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soil_moisture_readings', schema=None) as batch_op:
        batch_op.create_index('ix_smr_field_taken', ['field_id', 'taken_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_soil_moisture_readings_field_id'), ['field_id'], unique=False)

    op.create_table('farmer_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('useful', sa.Boolean(), nullable=True),
    sa.Column('did_irrigate', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['irrigation_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_feedback_recommendation_id'), ['recommendation_id'], unique=False)

    op.create_table('irrigation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('irrigated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('amount_mm', sa.Float(), nullable=True),
    sa.Column('liters', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['irrigation_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_irrigation_idempotency')
    )
    with op.batch_alter_table('irrigation_events', schema=None) as batch_op:
        batch_op.create_index('ix_ie_field_time', ['field_id', 'irrigated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_irrigation_events_field_id'), ['field_id'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('quality_flag', sa.String(length=24), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_readings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index('ix_sensor_readings_sensor_ts', ['sensor_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_sensor_readings_sensor_ts')
        batch_op.drop_index(batch_op.f('ix_sensor_readings_sensor_id'))

    op.drop_table('sensor_readings')
    with op.batch_alter_table('irrigation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_irrigation_events_field_id'))
        batch_op.drop_index('ix_ie_field_time')

    op.drop_table('irrigation_events')
    with op.batch_alter_table('farmer_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_feedback_recommendation_id'))

    op.drop_table('farmer_feedback')
    with op.batch_alter_table('soil_moisture_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soil_moisture_readings_field_id'))
        batch_op.drop_index('ix_smr_field_taken')

    op.drop_table('soil_moisture_readings')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_field_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('irrigation_recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_rec_field_computed')
        batch_op.drop_index(batch_op.f('ix_irrigation_recommendations_field_id'))

    op.drop_table('irrigation_recommendations')
    with op.batch_alter_table('advisories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisories_field_id'))

    op.drop_table('advisories')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_farm_id'))

    op.drop_table('fields')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notif_user_unread')

    op.drop_table('notifications')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_farmer_id'))

    op.drop_table('farms')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_ts')

    op.drop_table('audit_logs')
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_observations_lat_key'))
        batch_op.drop_index('ix_weather_obs_latkey_ts')

    op.drop_table('weather_observations')
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_forecasts_lat_key'))

    op.drop_table('weather_forecasts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('soil_types')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_due')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    op.drop_table('crops')
    # ### end Alembic commands ###
